# Default Configuration File for Cops and Robbers -ProSl3nderMan
lobby:
  world: world
  x: 0
  y: 64.0
  z: 0
nextmap: 4
map1:
  world: world
  cellamount: 0.0
  rg:
    win:
      block1: 
      block2: 
map2:
  world: world
  cellamount: 0.0
map3:
  world: world
  cellamount: 0.0